/* eslint-disable import/prefer-default-export */
import React from 'react';
import { FaEye } from 'react-icons/fa';

export const students = [
  {
    name: 'Chirag Gondaliya',
    email: 'abcorg@gmail.com',
    number: '+91 6353264115',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '10th',
    enrollment: '45675467',
    enrollmentName: 'enrollment',
  },
  {
    name: 'Namya Gondaliya',
    email: 'abcorg2@gmail.com',
    number: '+91 6353264116',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '9th',
    enrollment: '45675468',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'John Doe',
    email: 'johndoe@gmail.com',
    number: '+91 6353264117',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '11th',
    enrollment: '45675469',
    enrollmentName: 'enrollment',
  },
  {
    name: 'Jane Smith',
    email: 'janesmith@gmail.com',
    number: '+91 6353264118',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '12th',
    enrollment: '45675470',
    enrollmentName: 'enrollment',
  },
  {
    name: 'Michael Johnson',
    email: 'michaeljohnson@gmail.com',
    number: '+91 6353264119',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTISlGKcE78vh9ZCADuYZ7ZKi15wgU2pydPA&s',
    icon: <FaEye />,
    standardName: 'Standard',
    standard: '8th',
    enrollment: '45675471',
    enrollmentName: 'enrollment',
  },
];
